spreadsheet_key = "1yCWeGfmGP5-RmZzlDspHA2ayJSFoIzar1TjhIaqtP_o"
mongo_uri = "mongodb+srv://edenEldar:Eden1996@cluster0.rwebk7f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
buldog_spreadsheet_key = "12An-o3IOST2FEKrwc8-j2M6CxMCEms3sbI3xhAmahK0"
nova_subject_list_key = "1Q8kqM3T4svMboJWKeUYTHUgyBAnVDqghIzwBtmg79Wc"
fibro_ema_sheet = "1sTD5EoVHttWIDuNEt30hyA3NRDsVwsSYtmPGInWR8PA"
edenede2 = "Admin, Admin"
omri.radai = "Manager, nova"
gideon.lossin = "Manager, nova"
lrj1081 = "Student, nova"
barkroi7892 = "Student, nova"

[gcp_service_account]
type = "service_account"
project_id = "fitbit-cron"
private_key_id = "e38e08db53e5f8b69778adee46524e6d1e3b3125"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD07CUnV6pWlkpX\nlZxBBUuWG8OrQmzEYqq/29BqAJj2KMxtO95DSJ148GWbbqZ+Gt4tDd8N0EBZKkxG\n5aMN4OhFI1ypm6aExe2jfZvkfpjbF/jM6cfuoJB7jaf0nlod1CqG98Mcojg1/sTG\n2MZL+ZQb3UQO2PuidsYjtIYd6rPWocTiGTRoETOYuL/Xhxtr5sAdqnfvXPb7Dl5W\nkEQAE5IEPMzChnjuEVWIy9MhtFoijBi1vi4CAAsdXcjkwXNMwblSBwCqnlSIw7wB\nwp0GMMnoUczD5YRltZpTt0LOfsZRPDrth85qFHTHoNncXxpMicoKnFtnvIXTtVNH\nQwhu6Pf5AgMBAAECggEAct0S2Z4gCUanq+bC5q2EkuwHepiG6R065grBdg08r2lX\n4jzLErQKAi9//4LHu2l/XBLe0pwhqY+QQUmuDDK3y8D3UqXoVOl8dwnQJDuJFWtr\nKDLVrKCJ0iAPrkXbjpSzsyOcUh/0C8KlZ3o/mV79qom9QtdZQArDBvjBU2OAnv3J\nNJU6Pzq1MdadHiHpq3/z1agerlZbJ8FemNVZtyewdEZE8a3+Hl9dyyFO1x2NwL2c\n1yTcp5ZqwgAGwXkc9SfcIgOXCgNCHChk/j/1DXfzYOyHd2sONR3TJayoA5zwi7VN\n3FzCu+NEHCbUMWZMwwo9C6Qyk3XYvY3+nqoWWywx7wKBgQD9jrUeMbZY1cjvziUk\nRDD2dJ0BcAmij4J+UZKNrDjsDavvNs7BUzRFKlidzsJ8JgpVrjPt+tNPn8k8Llxz\nBT9QOnPdiABVCBb1H/laTbXFPa1LsWdPNmR+GHdzdAlWOQI1pkmBkigeyRoDB657\njhd5Eiexl/KSv8QT7CtridKs4wKBgQD3SCSdtPIQ/feHqr0PAq6TenwbwHiz4Au1\nJ/YbeOlD15V1BQ+lNg9zG03MWkRY8mV86JVIoeeG5I0LAL/xevsVsHu2DDjKLiQ6\nVLMOixyayacYcB7eCBLpCVSLNNHdattmr6PBqqZzSur4GHBq9XokC1CkZo0KhFNL\n60N7c4TacwKBgAM5CiJNHXU5mmk55Iz2dOzdBJXdF7JCQrVaUhOM6dhOQC41MyGP\n7i0m4aN32k77qMv3/975fjAX5tXl/PTVTz200H4zWVW7WZdaBbBZJoNQSmCY66g9\nF7/mjbYg9nFrHhUSfQKxmeLySWtacKRPZQr76Rc/yCyHVXWvXcnrIYtjAoGAHM3o\nhf5X3CbZOJJo52C2mTNBVbI73SgR9Q4smtKgyWhJXpIyWlpLvmrFyzIQmBPUQpKN\nISLK52mkDE4QDb73lHU0U+ZkjxiE286V9PG7aURoFG6rCc4C9eZCVNzYPWR/Hh0D\nhEGulet6J2AhaDQkACLZR+0yLLFxSnyjJbQ1G4UCgYEAzUKc8bF4C6dCr1IDxZ/B\nj93SuQzc0pEIGB9RYnee+R7ZkKoP0fiD79ejQCvio6IGIztR4j0nI6di3+ydLdl0\nV0RaiFrLGd4R7p6abVc49BLat7OS5ngIH4oMRzu9oS3DeJ0OgAu+2Ik+iAJjdAzF\ndo9C7cMR5j0k7CfsHZLufQM=\n-----END PRIVATE KEY-----\n"
client_email = "fitbitmanagment@fitbit-cron.iam.gserviceaccount.com"
client_id = "107046123291827950893"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/fitbitmanagment%40fitbit-cron.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[app_users]
passwords = ["$2b$12$z5yPhrVhJ95eT.ZNEUeDdejxDsC/GMUt00DdW6l7ZovML22Qzq.2a","$2b$12$3AskHDTTC8D.UOuDh3KMsOaJOnfE4CEuKns2Ru0XtDLE588vz1QoW","$2b$12$bB8LclaEo1rhZzoZOI0NJuoi5R2rl1eC2iK789pdEJd3F4ftjQYGS"]

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "j8nX4pL7qT2wE9zS3rA5vB6yC1mD0oF8gH7jK3lP2xZ"

[auth.google]
client_id = "838077653521-g0g7ptjkr8u5070m9r7fs1g6jjr0dos7.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"